### ISSUE TITLE
Suggest new name to the package

### ISSUE THREAD

**Issue by mbad0la** [o-d-i-n/is-alpha#3]
In order to expand the functionality of this package, we'd have to go beyond simple language validation. In such a scenario, is-alphabet doesn't seem like a fit name to the node module. Any suggestions are more than welcome.

**Comment by karanchahal** [comment]
How about "isValid" or validateJs. A play on the words valid I think shall suffice because I think ,and I could be wrong,that this rep is meant to be a quick tool for checking various validity concerns.
And thinking in that vein gives me a few ideas on how this rep could be extended
Email,Password Validation could be added too
Though How exactly password validation would work ,I'm not too sure about.

**Comment by mbad0la** [comment]
Let's see what the consensus is about functionality expansion as it might take away the simplicity of this package.

**Comment by mbad0la** [comment]
It has been dediced to keep the package functionality as is.
